---
  - name: "{{playbook_name}}"
    hosts: "{{hosts}}"
    gather_facts: "{{facts}}"
    vars_files: "variables/test.yaml"
      
    tasks: 
      - name: Ping "{{hosts}}"
        ping:
        
      - name: Read Variable
        debug:
          msg: "{{ test_message }}"
      
      - name : Run "{{custom_command}}"
        shell: 
          cmd: "{{custom_command}}"

      