---
  - name: "{{ play_name }}"
    hosts: "{{ servers }}"
    vars:
      facts: no
    vars_files:
       - "install_packages_play-vars.yaml"   #steps is important. variable file consider last file as priority 
       - "install_packages_tasks-vars.yaml"    # do not give different value as a one key
    gather_facts: "{{ facts }}"
    tasks:
      - name: Install packages on CentOS # when we install "htop" we have to define and make epel-release. 
        when: ansible_facts['distribution'] == "CentOS" # that is why our fist task is epel-release
        yum: 
          name: "{{ centos_packages }}"
          state: latest
          
      - name: Install packages 
        when: 
          - ansible_facts['distribution'] == "CentOS"
        yum:
          name: "{{ centos_packages }}" 
          state: latest

      - name: Install packages on Ubuntu
        when: 
          - ansible_facts['distribution'] == "Ubuntu"
        apt:
          name: "{{ ubuntu_packages }}"     
          state: latest
      